version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      python-runtime:
        patterns: ["*"]

  - package-ecosystem: "pip"
    directory: "/rules-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      python-runtime:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      docker-runtime:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/rules-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      docker-runtime:
        patterns: ["*"]

  - package-ecosystem: "terraform"
    directory: "/terraform/bootstrap"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      terraform-providers:
        patterns: ["*"]

  - package-ecosystem: "terraform"
    directory: "/terraform/ecr"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      terraform-providers:
        patterns: ["*"]
